### PR TITLE
"Fix" GFM tasklist rendering

### PR DESCRIPTION
**Pull request by bobhy**
Resolves the issues raised in #805.

Changes html rendering for GFM tasklists from:
```html
<p>Old task list</p>
<ul>
<li><input disabled="" type="checkbox"/>do it</li>
<li><input disabled="" type="checkbox" checked=""/>done</li>
</ul>
<p>
New task list
</p>
<ul>
<li style="list-style-type: '\2610   ';">to do</li>
<li style="list-style-type: '\2612   ';">done</li>
</ul>
```
Which renders as:
image

Apparently the former rendering is specified in Commonmark specs, so we should raise the question, potentially get a blessing from them.  What's that process?

I don't know when `list-style-type: <string>` was released in CSS.  Current Firefox, Edge and Chrome browsers support it, someone will need to try Safari.

`\2612` for the "checked" marker renders as a box with an X, not a checkmark.  That's my personal preference, but it's just Unicode and there's a `\2611` that has the checkmark.

This is a modestly breaking change (for code that depends on HTML output).  Should there be an `old_gfm_task_render` feature?

### CODE REVIEW

**Comment by bobhy** [comment]
OK. Yet another enhancement request that's not quite ready for prime time.
Meantime, I've got my private repo integrated with Zola and am able to use
it for what I needed.

Is there any energy about doing a new release of the project?  Enhancements
are always nice, though the simple bug reports seem to be piling up.  I've
got some time and interest, would be willing to join the fun.

My idea would be to focus first on a bug-fix release.  That gives you more
time to design thoughtful enhancements or add ons and the confidence that
you've got a solid codebase to work from.  I could take a crack at
identifying issues that might be good candidates for such a release,
hopefully that makes it easier for others who have time to know where to
pitch in.

**Comment by Martin1887** [comment]
Hello, the 0.10 version will be released when the pending pull requests are merged, hopefully this month.

However, new contributors are welcome, and indeed I had planned creating a new issue asking for contributors after the 0.10 release. To join as contributor, it is recommended to have a meeting with @raphlinus, and it is required respecting the rule of not merging pull requests or commits to the `master` branch without approval from another person.

@notriddle, @ollpu and @mgeisler are good candidates, based on previous contributions, but everyone is welcome.

Thanks!

**Comment by ollpu** [comment]
Hey, thanks for the recognition. I'm open to dedicating some on-and-off time to maintaining the project.

**Comment by Martin1887** [comment]
Hi, the project has been moved to a new organization and I have invited @ollpu and @notriddle to join as contributors of the project.

I have just created a v0.11 milestone with the most important issues for the 0.11 release, but discussion is open to add other ones.

**Comment by mgeisler** [comment]
> @notriddle, @ollpu and @mgeisler are good candidates, based on previous contributions, but everyone is welcome.

I would be happy to contribute where possible, but I have to admit that I find it hard to find time for my own crates these days... I'll of course keep trying to add a comment here and there when I find time :smile:

**Comment by Martin1887** [comment]
This change is more adequate in an alternative renderer, as @notriddle said, and it is already added in the tracking issue.

**Pull request closed without merging**
