### PR TITLE
feat: add `-D` CLI option to enable definition lists

### PR DESCRIPTION
**Pull request by ytmimi**

### CODE REVIEW

**Comment by ytmimi** [comment]
Happy to make the change, though I think CI is failing because of https://github.com/rust-lang/rust/pull/131833 and not my change. This is the error from the logs:

```
error: unused return value of `exec` that must be used
   --> dos-fuzzer/src/main.rs:282:25
    |
282 |                         Command::new(&args[0]).args(&args[1..]).exec();
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D unused-must-use` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_must_use)]`
help: use `let _ = ...` to ignore the resulting value
    |
282 |                         let _ = Command::new(&args[0]).args(&args[1..]).exec();
    |                         +++++++

error: could not compile `dos-fuzzer` (bin "dos-fuzzer") due to 1 previous error
```

**Comment by ollpu** [comment]
This clashes with `-D` i.e. `--enable-subscript`

**Comment by ytmimi** [comment]
@ollpu I don't think `--enable-subscript` was available when I put this PR together.

**Comment by ytmimi** [comment]
@ollpu yeah, looks like https://github.com/pulldown-cmark/pulldown-cmark/pull/966 configured `-D` for `--enable-subscript`, when it was already being used for definition lists.

**Comment by ollpu** [comment]
Ah, my bad, I just went by the order they were in `--help`. We'll get this sorted

**Pull request merged**
