### PR TITLE
Implement commonmark-hs compatible definition lists

### LINKED ISSUE #67: Support for Description Lists
Some parsers have an extension to support description/definition lists. In https://talk.commonmark.org/t/description-list/289 there is a proposal to add it to CommonMark. A common syntax is to put a colon at the beginning of the line.

An example from the [Pandoc manual](http://pandoc.org/MANUAL.html#definition-lists):

```
Term 1

:   Definition 1

Term 2 with *inline markup*

:   Definition 2

        { some code, part of Definition 2 }

    Third paragraph of definition 2.
```

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #67

### CODE REVIEW

**Comment by Martin1887** [comment]
Awesome! But I think it would be better to merge it in the new `branch_0.12` branch I have just created, because the last changes probably deserve a new 0.11 minor release.

Also, I wonder if the number of calls to `self.finish_list` in `firstpass.rs` could be reduced by dividing it into a function for normal lists and another one for description lists or something else. It seems the only messier part of the code respect to the previous version.

Thanks!

**Comment by Martin1887** [comment]
A lot of time since the last update and I don't get a cleaner manner of doing it, so let's merge it. Thanks!

**Comment by alyjak** [comment]
It looks like the definition lists do not work if they are embedded in another block type. Both of these examples are failing for me on v0.12.2 with the following panic: 

```panicked at /home/alyjak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-0.12.2/src/firstpass.rs:1540:38:
called `Option::unwrap()` on a `None` value`.
```

``` markdown
>
> A definition
> : embedded in a quote
>
```

Or this

``` markdown
A definition
:   an embedded term
   :   embedd definition
```

Is this expected behavior? Thanks for the hard work. I really appreciate this library.

**Comment by Martin1887** [comment]
Please open a new issue with this problem, thanks!

**Comment by Martin1887** [comment]
Please open a new issue with this problem, thanks!

**Comment by Martin1887** [comment]
Please open a new issue with this problem, thanks!

**Pull request merged**
